# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
# Examples:
#  * https://gist.github.com/vilmibm/a1b9a405ac0d5153c614c9c646e37d13
#  * https://github.com/vEnhance/dotfiles/blob/main/gh-config.yml
#  * https://github.com/aaronpowell/system-init/blob/master/common/gh-config.yml
#  * https://github.com/cli/cli/issues/1200#issuecomment-659921986
aliases:
    aliases: alias list
    prs: pr list
    prv: pr view
    pro: pr checkout
    co: pr checkout
    prc: pr create
    prci: |-
        !(
            branch_name=$(gh __branch-name)
            wi_id=$(echo ${branch_name} | awk -F'_' '{print $1}')
            wi_title=$(echo ${branch_name} | awk -F'_' '{print $2}')

            wi_id_azdo=$(echo ${wi_id} | tr '-' '#')
            wi_title_azdo=$(echo ${wi_title} | tr '-' ' ')

            pr_title="${wi_id_azdo} ${wi_title_azdo}"
            pr_body="${wi_id_azdo}"
            
            # Remove next line when https://github.com/cli/cli/issues/1718 is fixed
            git push -u origin HEAD
            
            gh prc \
                --title "${pr_title}" \
                --body "${pr_body}" \
                --draft
        )
    approve: pr review --approve
    pr-approve: |-
        !(
            pr_id=""
            [ $# -eq 1 ] && pr_id=$1
            [ -z "${pr_id}" ] && pr_id=$(gh pr list | fzf | awk '{print $1}')
            gh pr-approve-id "${pr_id}"
        )
    pr-approve-last: |-
        !(
            pr_id=$(gh pr list | head -n1 | awk '{print $1}')
            gh pr-approve-id "${pr_id}"
        )
    pr-approve-id: |-
        !(
            if [ $# -ne 1 ]; then
                echo "Usage: gh pr-approve-id [pr_id|branch_name|pr_url]"
                exit 1
            fi
            pr="$1"
            gh pr review \
                ${pr} \
                --approve \
                --body "approved from gh cli"
        )
    pr-merge: |-
        !(
            branch_name=$(gh __branch-name)
            gh pr merge \
                ${branch_name} \
                --auto \
                --squash \
                --delete-branch
        )
    codespaces: codespace list
    configs: config list
    clo: repo clone "$1"/"$2"
    repos: repo list
    repos-name-all: |-
        !(
            user=${1:-$USER}
            gh api --paginate graphql -f owner="${user}" -f query='
                query($owner: String!, $per_page: Int = 100, $endCursor: String) {
                    repositoryOwner(login: $owner) {
                        repositories(first: $per_page, after: $endCursor, ownerAffiliations: OWNER) {
                            nodes { name }
                            pageInfo { hasNextPage endCursor }
                        }
                    }
                }
            ' | jq -r '.data.repositoryOwner.repositories.nodes[].name' | sort
        )
    alerts: |-
        !(
        
            gh repo-dependabot-alerts  
        )
    repo-dependabot-alerts: |-
        !(
            user=${1:-$USER}
            repo=${2:-$REPO}
            gh api --paginate graphql -f owner="${user}" -f name="${repo}" -f query='
                query($owner: String!, $name: String!, $per_page: Int = 100, $endCursor: String) {
                    repository(owner: $owner, name: $name) {
                        vulnerabilityAlerts(first: $per_page, after: $endCursor) {
                            nodes {
                                createdAt
                                dismissedAt
                                securityVulnerability {
                                    package {
                                        name
                                    }
                                    advisory {
                                        description
                                    }
                                }
                            }
                            pageInfo { hasNextPage endCursor }
                        }
                    }
                }
            '
        )
    repos-name: |-
        !(
            user=${1:-$USER}
            gh repo list "${user}" --limit 9999 --json "name" --jq ".[].name"
        )
    # https://github.com/matt-bartel/gh-clone-org
    clo-org: clone-org
    clone-repos-all: |-
        !(
            user=${1:-$USER}
            gh repos-name-all "${user}" | xargs -I '%' gh repo clone ${user}/%
        )
    clone-all-repos: |-
        !(
            user=${1:-$USER}
            gh clone-repos-all ${user}
        )
    issues: issue list
    releases: release list
    runs: run list
    runs-branch: |-
        !(
            gh run list --branch=$(git branch --show)
        )
    execute-workflow-branch: |-
        !(
            
            if [ $# -lt 1 ]; then
                echo "Usage: gh execute-workflow-branch <workflow_filename> [workflow_args]"
                exit 1
            fi
            workflow_file="$1"; shift
            if [ -z "$workflow_file" ]; then
                echo "<workflow_file> is required"
                exit 1
            fi
            workflow_args="$@"
            workflow_name_to_run=$(yq '.name' ${workflow_file})
            branch_name=$(gh __branch-name)
            gh workflow run "${workflow_name_to_run}" --ref "${branch_name}" ${workflow_args}
        )
    secrets: secret list
    ssh-keys: ssh-key list
    workflows: workflow list
    list-milestones: |-
        api graphql -F owner=':owner' -F name=':repo' -f query='
            query ListMilestones($name: String!, $owner: String!) {
                repository(owner: $owner, name: $name) {
                    milestones(first: 100) {
                        nodes {
                            title
                            number
                            description
                            dueOn
                            url
                            state
                            closed
                            closedAt
                            updatedAt
                        }
                    }
                }
            }
        '
    lm: |-
        !(
            gh list-milestones | jq '.data.repository.milestones.nodes[]'
        )
    rate-limit: |-
        !(
            gh api \
                -H "Accept: application/vnd.github.v3+json" \
                /rate_limit
        )
    rate-limit-table: |-
        !(
            gh api \
                -H "Accept: application/vnd.github.v3+json" \
                /rate_limit \
            | jq '.resources' \
            | jq -r '(["LIMIT","USED","REMAINING","RESET"] | (., map(length*"-"))), (.[] | [.limit, .used, .remaining, .reset]) | @tsv'
        )
    # typos
    lsit: list
    # private
    __branch-name: |-
        !(
            git rev-parse --abbrev-ref HEAD
        )
    

# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
