#!/usr/bin/env bash

# https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories
if [ -f .pre-commit-config.yaml ]; then
    echo 'pre-commit configuration detected, but `pre-commit install` was never run' 1>&2
    exit 1
fi

# trunk hooks detection
if [ -f .trunk.yaml ] || [ -f .trunk.yml ] || [ -f .trunk/trunk.yaml ] || [ -f .trunk/trunk.yml ]; then
    echo 'trunk hooks detected, but `trunk install` was never run' 1>&2
    exit 1
fi