wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    ipinfo:
      enabled: false
      colors:
        name: "lightblue"
        value: "white"
      position:
        top: 0
        left: 0
        height: 1
        width: 2
      refreshInterval: 150      
    github:
      enabled: true
      enableStatus: true
      apiKey: ""
      baseURL: ""
      customQueries:
        pezaioPR:
          title: "Pezaio Pull Requests"
          filter: "org:pezaio is:open is:pr"
        nomupayPR:
          title: "NomuPay Pull Requests"
          filter: "org:nomupay is:open is:pr"
      position:
        top: 0
        left: 0
        height: 2
        width: 4
      refreshInterval: 5m
      repositories:
        - "pezaio/hades-team"
        - "pezaio/infrastructure"
        - "pezaio/handbook"
        - "pezaio/admin"
      uploadURL: ""
      username: "svg153"
    power:
      enabled: false
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"